import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {DatabaseSync} from 'node:sqlite';import {JSDOM,VirtualConsole} from 'jsdom';import {createWorker} from '../src/worker.mjs';
const bundle=JSON.parse(await readFile('.local/bundle.json','utf8'));const html=await readFile('ui/index.html','utf8'),script=await readFile('ui/editor.js','utf8');
const leaf=bundle.manifest.find(n=>n.text==='MAKE ROOM.');
function backend(){
 const db=new DatabaseSync(':memory:');
 db.exec('CREATE TABLE editor_projects(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL,version INTEGER NOT NULL,state_json TEXT NOT NULL,updated_at TEXT NOT NULL)');
 const DB={prepare(sql){return {bind(...args){return {
   async first(){return db.prepare(sql).get(...args)||null;},
   async run(){return {meta:{changes:Number(db.prepare(sql).run(...args).changes)}};}
 };}};}};
 const env={EDITOR_OWNER_USER_ID:'test-owner',DB};
 const worker=createWorker(bundle);
 return {async fetch(path,opts={}){return worker.fetch(new Request('https://editor.test'+path,{...opts,headers:{...opts.headers,'oai-authenticated-user-id':'test-owner'}}),env);}};
}
async function until(condition){for(let i=0;i<100;i++){if(condition())return;await new Promise(r=>setTimeout(r,5));}throw Error('DOM condition not reached');}
async function open(api,path='/'){const errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!e.message.includes('navigation'))errors.push(e.message)});const dom=new JSDOM(html,{url:'https://editor.test'+path,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window;w.fetch=(...args)=>api.fetch(...args);w.crypto.randomUUID=()=>crypto.randomUUID();w.confirm=()=>true;w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')};w.eval(script);await until(()=>w.document.querySelector('#status').textContent.includes('Guardado')||w.document.querySelector('#status').textContent.includes('Viendo'));return {dom,w,d:w.document,errors};}
const click=(d,s)=>d.querySelector(s).click();function input(w,s,value){const el=w.document.querySelector(s);el.value=value;el.dispatchEvent(new w.Event('input',{bubbles:true}));}
async function editSave(ui,text){click(ui.d,`[data-id="${leaf.id}"]`);input(ui.w,'#text-edit',text);input(ui.w,'[data-prop="font-size"]','70');input(ui.w,'[data-prop="color"]','#aabbcc');ui.d.querySelector('#inspector').dispatchEvent(new ui.w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>ui.d.querySelector('#review-dialog').hasAttribute('open'));await until(()=>!ui.d.querySelector('#commit').disabled);click(ui.d,'#commit');await until(()=>!ui.d.querySelector('#review-dialog').hasAttribute('open'));await until(()=>ui.d.querySelector('#status').textContent.includes('Guardado'));}
test('DOM workflow: source save, reload, undo/reload, redo, and dirty confirmation',async()=>{const api=backend();let ui=await open(api);await editSave(ui,'NEW DRAFT.');let project=await(await api.fetch('/api/project')).json();assert.equal(project.edits[leaf.id].text,'NEW DRAFT.');assert.equal(project.edits[leaf.id].styles['font-size'],'70px');assert.equal(project.edits[leaf.id].styles.color,'#aabbcc');ui.dom.window.close();ui=await open(api);click(ui.d,`[data-id="${leaf.id}"]`);assert.equal(ui.d.querySelector('#text-edit').value,'NEW DRAFT.');input(ui.w,'#text-edit','UNSAVED');let confirms=0;ui.w.confirm=()=>{confirms++;return false};click(ui.d,'#undo');assert.equal(confirms,1);assert.equal(ui.d.querySelector('#text-edit').value,'UNSAVED');assert.equal((await(await api.fetch('/api/project')).json()).head,'r1');ui.w.confirm=()=>true;click(ui.d,'#undo');await until(()=>ui.d.querySelector('#status').textContent.includes('r2'));ui.dom.window.close();ui=await open(api);click(ui.d,`[data-id="${leaf.id}"]`);assert.equal(ui.d.querySelector('#text-edit').value,'MAKE ROOM.');click(ui.d,'#redo');await until(()=>ui.d.querySelector('#status').textContent.includes('r3'));assert.equal(ui.d.querySelector('#text-edit').value,'NEW DRAFT.');assert.deepEqual(ui.errors,[]);ui.dom.window.close();});
test('DOM historical links open requested source revision readonly and return to latest draft',async()=>{const api=backend();let ui=await open(api);await editSave(ui,'CURRENT HEAD.');ui.dom.window.close();ui=await open(api,'/?revision=r0');assert.match(ui.d.querySelector('#preview').src,/revision=r0/);click(ui.d,`[data-id="${leaf.id}"]`);assert.equal(ui.d.querySelector('#text-edit').value,'MAKE ROOM.');assert.equal(ui.d.querySelector('#text-edit').disabled,true);assert.equal(ui.d.querySelector('#undo').disabled,true);assert.equal(ui.d.querySelector('#add-comment').disabled,true);click(ui.d,'#compare');await until(()=>ui.d.querySelector('#status').textContent.includes('Guardado'));assert.equal(ui.d.querySelector('#text-edit').value,'CURRENT HEAD.');assert.deepEqual(ui.errors,[]);ui.dom.window.close();});
test('DOM canceled review preserves inputs and proposal can be reviewed again',async()=>{const api=backend();const ui=await open(api);click(ui.d,`[data-id="${leaf.id}"]`);input(ui.w,'#text-edit','A PROPOSAL.');ui.d.querySelector('#inspector').dispatchEvent(new ui.w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>ui.d.querySelector('#review-dialog').hasAttribute('open'));await until(()=>!ui.d.querySelector('#cancel-review').disabled);click(ui.d,'#cancel-review');await until(()=>!ui.d.querySelector('#review-dialog').hasAttribute('open'));assert.equal(ui.d.querySelector('#text-edit').value,'A PROPOSAL.');assert.equal((await(await api.fetch('/api/project')).json()).head,'r0');assert.equal(ui.d.querySelector('#review').disabled,false);assert.deepEqual(ui.errors,[]);ui.dom.window.close();});
