'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],copy=x=>JSON.parse(JSON.stringify(x));
const frame=$('#preview');
let project,selected,working={},viewport=1440,nonce,frameRevision,comparing=false,pending,busy=false,gesturing=false,ready=false;
let viewRevision=new URL(location.href).searchParams.get('revision'),viewEdits=null,undoLocal=[],redoLocal=[],saveKey=null;
const flushes=new Map();
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const scopeName=()=>viewport>=1024?'desktop':viewport>=768?'tablet':'mobile';
function status(text,error=false){$('#status').textContent=text;$('#status').toggleAttribute('data-error',error);}
async function action(name,args={}){const response=await fetch('/api/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:name,args})});const result=await response.json();if(!response.ok){const error=new Error(result.error?.message||'No se pudo guardar');error.code=result.error?.code;throw error;}return result;}
function changesToSave(){
 const changes=[];for(const n of project?.manifest||[]){const a=project.edits[n.id]||{},b=working[n.id]||{};
  if((a.text??n.text)!==(b.text??n.text))changes.push({element_id:n.id,text:b.text??n.text});
  for(const scope of ['global','desktop','tablet','mobile']){const before=scope==='global'?a.styles||{}:a.responsive?.[scope]||{},after=scope==='global'?b.styles||{}:b.responsive?.[scope]||{},styles={};for(const [key,value]of Object.entries(after))if(before[key]!==value)styles[key]=value;if(Object.keys(styles).length)changes.push({element_id:n.id,styles,...(scope==='global'?{}:{viewport:scope})});}
 }return changes;
}
const dirty=()=>!!changesToSave().length;
const editable=()=>!comparing&&!viewRevision&&!pending&&!busy;
function post(type,data={}){if(!project)return;frame.contentWindow.postMessage({type,project_id:project.project_id,revision_id:frameRevision,nonce,...data},'*');}
function config(){post('ve:configure',{editable:editable()});}
function syncCanvas(){if(comparing||pending)return;const edits={};for(const [id,edit]of Object.entries(viewEdits||working))edits[id]={...('text'in edit?{text:edit.text}:{}),styles:{...edit.styles,...edit.responsive?.[scopeName()]}};post('ve:sync',{edits});}
async function flushCanvas(){if(!ready)return;await new Promise(resolve=>{const id=crypto.randomUUID();const timer=setTimeout(()=>{flushes.delete(id);resolve();},700);flushes.set(id,()=>{clearTimeout(timer);resolve();});post('ve:flush',{request_id:id});});}
async function lock(fn){if(busy)return;busy=true;updateButtons();try{await fn();}catch(error){status(error.code==='REVISION_CONFLICT'?`${error.message} Tus ajustes siguen aquí. Exportalos antes de recargar.`:error.message,true);}finally{busy=false;updateButtons();}}
function updateButtons(){if(!project)return;const blocked=busy||gesturing||!!viewRevision||comparing||!!pending;$('#undo').disabled=blocked||(!undoLocal.length&&!project.canUndo);$('#redo').disabled=blocked||(!redoLocal.length&&!project.canRedo);$('#save').disabled=blocked||!dirty();$('#export').disabled=busy;$('#review').disabled=blocked||!dirty();$('#commit').disabled=busy||!pending;$$('#inspector input,#inspector textarea,#inspector select').forEach(x=>x.disabled=blocked);$('#add-comment').disabled=blocked||!selected;$('#cancel-review').disabled=busy;$('#cancel-review-bottom').disabled=busy;$('#export-unsaved').hidden=!dirty();$('#export-unsaved').disabled=busy;config();}
async function load({preserveInputs=false}={}){
 const response=await fetch('/api/project'),data=await response.json();if(!response.ok)throw new Error(data.error?.message||'No se pudo abrir el proyecto');if(preserveInputs&&project){const stale=data.head!==project.head;project.feedback=data.feedback;renderComments();if(stale)status('La fuente cambió en otra pestaña. Tus ajustes conservan su revisión base; recargá después de exportarlos.',true);return;}project=data;
 if(!preserveInputs){working=copy(project.edits);undoLocal=[];redoLocal=[];saveKey=null;}
 $('[data-prop="font-family"]').innerHTML=project.available_fonts.map(f=>`<option>${esc(f)}</option>`).join('');$('.project-heading strong').textContent=project.name;$('.project-heading div>span').textContent=project.subtitle;$('.frame-caption>span').textContent=project.pageLabel+' / INICIO';$('.source-version').textContent=project.revisionLabel;document.title='Atelier · '+project.name;
 if(viewRevision){if(!project.history.some(r=>r.id===viewRevision))throw new Error('La revisión del enlace no existe');const inspected=await action('inspect_page',{page_id:'home',revision_id:viewRevision});viewEdits=Object.fromEntries(inspected.elements.map(n=>[n.id,{...(n.text!==null?{text:n.text}:{}),styles:n.global_overrides||{},responsive:n.responsive||{}}]));}
 renderLayers();renderHistory();renderTaste();$('#loading').hidden=true;if(!preserveInputs){renderFrame();if(selected)showSelection(selected);}updateButtons();
 status(viewRevision?`Viendo ${viewRevision} · solo lectura · actual ${project.head}`:`Guardado · ${project.head} · borrador fuente`);
}
function displayedText(n){return comparing?n.text??'':(viewEdits||working)[n.id]?.text??n.text??'';}
function displayedLabel(n){return n.text&&n.label===n.text.slice(0,38)?displayedText(n).slice(0,38):n.label;}
function renderLayers(){const q=$('#layer-search').value.toLowerCase(),rows=project.manifest.filter(n=>!q||`${displayedLabel(n)} ${displayedText(n)}`.toLowerCase().includes(q));$('#layer-count').textContent=project.manifest.length;$('#layers').innerHTML=rows.map(n=>`<button class="layer ${selected?.id===n.id?'selected':''}" data-id="${n.id}" data-depth="${Math.min(n.depth,4)}"><span class="layer-symbol">${/^h[123]$/.test(n.tag)?'T':n.text?'t':'◇'}</span><span class="layer-label">${esc(displayedLabel(n))}</span></button>`).join('');}
function sizeFrame(){const available=$('.canvas-scroll').clientWidth-(innerWidth<560?24:innerWidth<1100?30:48),scale=Math.min(1,Math.max(.05,available/viewport)),height=900;frame.style.width=viewport+'px';frame.style.height=height+'px';frame.style.transform=`scale(${scale})`;$('#frame-wrap').style.width=viewport*scale+'px';$('#frame-wrap').style.height=height*scale+'px';$('.frame-caption').style.width=viewport*scale+'px';$('#zoom').textContent=Math.round(scale*100)+'%';$('#viewport-label').textContent=`${viewport} × ${height}`;$('#style-scope').textContent={desktop:'Escritorio',tablet:'Tablet',mobile:'Móvil'}[scopeName()]+' · ajustes de esta vista';if(ready)requestAnimationFrame(()=>{syncCanvas();postSelection();});}
function renderFrame(rev){ready=false;nonce=crypto.randomUUID();frameRevision=rev||(comparing?'r0':viewRevision||project.head);frame.src=`/preview?revision=${encodeURIComponent(frameRevision)}&nonce=${nonce}`;$('#revision-badge').textContent=comparing?'ORIGINAL · r0':frameRevision.startsWith('patch:')?'PROPUESTA':frameRevision;sizeFrame();}
function postSelection(scroll=false){if(selected)post('ve:select',{element_id:selected.id,scroll});}
function showSelection(n,computed){selected=n;$('#selection-empty').hidden=true;$('#inspector').hidden=false;$('#element-tag').textContent=n.tag;$('#element-name').textContent=displayedLabel(n);$('#source-map').textContent=`${n.source.file}:${n.source.line}`;$('#selection-path').textContent=`${n.tag} / ${displayedLabel(n)}`;$('#text-label').hidden=!n.editable.text;$('#text-edit').value=displayedText(n);$('#locked-reason').textContent=n.lockedReason||'';$('#locked-reason').hidden=!n.lockedReason;fillStyles(computed||{});renderLayers();renderComments();updateButtons();}
function toHex(value){if(/^#[\da-f]{6}$/i.test(value))return value;const m=value?.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);return m?'#'+m.slice(1).map(x=>Number(x).toString(16).padStart(2,'0')).join(''):'#111110';}
function fillStyles(computed){const edit=(comparing?{}:viewEdits||working)[selected.id]||{},saved={...edit.styles,...edit.responsive?.[scopeName()]};for(const input of $$('[data-prop]')){const prop=input.dataset.prop;let value=saved[prop]??computed[prop]??'';if(prop==='font-family'){value=value.split(',')[0].replaceAll('"','').replaceAll("'",'').trim();if(![...input.options].some(x=>x.value===value))value='Arial';}else if(prop==='color'||prop==='background-color')value=toHex(value);else if(prop==='line-height'){const n=Number.parseFloat(value);value=value.includes('px')?(n/(Number.parseFloat(computed['font-size'])||16)).toFixed(2):Number.isFinite(n)?n:1.2;}else if(prop!=='font-weight'){value=parseFloat(value);if(!Number.isFinite(value))value=0;}input.value=value;}}
function validStyles(styles){if(!styles||typeof styles!=='object'||Array.isArray(styles))return false;return Object.entries(styles).every(([key,value])=>project.manifest[0]?.editable.styles.includes(key)&&typeof value==='string'&&(key==='font-family'?project.available_fonts.includes(value):key.includes('color')?/^#[\da-f]{6}$/i.test(value):key==='font-weight'?/^(400|500|600|700|800|900)$/.test(value):key==='line-height'?/^(1(?:\.\d{1,2})?|2(?:\.0{1,2})?)$/.test(value):/^\d+(\.\d{1,2})?px$/.test(value)&&parseFloat(value)<=(key==='font-size'?220:key==='letter-spacing'?20:160)));}
function recordChange(id,change,transaction=crypto.randomUUID(),fromCanvas=false){
 if(!editable())return;const n=project.manifest.find(n=>n.id===id);if(!n)return;
 if('text'in change&&(!n.editable.text||typeof change.text!=='string'||!change.text.length||change.text.length>500||/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(change.text)))return;
 if(change.styles&&!validStyles(change.styles))return;
 const before=copy(working);working[id]??={};if('text'in change){if(change.text===(project.edits[id]?.text??n.text)&&!('text'in (project.edits[id]||{})))delete working[id].text;else working[id].text=change.text;}if(change.styles){working[id].responsive??={};working[id].responsive[scopeName()]={...working[id].responsive[scopeName()],...change.styles};}
 if(!Object.keys(working[id]).length)delete working[id];if(JSON.stringify(before)===JSON.stringify(working))return;
 const last=undoLocal.at(-1);if(last?.transaction===transaction){last.after=copy(working);if(JSON.stringify(last.before)===JSON.stringify(last.after))undoLocal.pop();}else undoLocal.push({before,after:copy(working),transaction});redoLocal=[];saveKey=null;
 if(selected?.id===id){if('text'in change)$('#text-edit').value=change.text;for(const [key,value]of Object.entries(change.styles||{})){const input=$(`[data-prop="${key}"]`);if(input)input.value=value.endsWith('px')?parseFloat(value):value;}}
 if(!fromCanvas)syncCanvas();renderLayers();updateButtons();status(`Sin guardar · ${changesToSave().length}/30 grupos de ajustes · Ctrl/Cmd+S para guardar`);
}
function renderHistory(){$('#history').innerHTML=[...project.history].reverse().map(r=>`<article class="history-item"><strong>${esc(r.id)} · ${esc(r.label)}</strong><p>${esc(new Date(r.createdAt).toLocaleString('es'))}</p>${r.revision_hash?`<p class="revision-hash">SHA-256 ${esc(r.revision_hash.slice(0,16))}…</p>`:''}${r.audit?.changes?.length?`<p>${r.audit.changes.length} cambios registrados</p>`:''}${r.id===project.head?'<span class="current">REVISIÓN ACTUAL</span>':`<button data-restore="${r.id}">Restaurar esta revisión ↶</button>`}</article>`).join('');}
function renderTaste(){$('#taste-rules').innerHTML=project.taste.decisions.map(d=>`<article class="taste-rule"><h3>${esc(d.scope)}</h3><p>${esc(d.rule)}</p><details><summary>Ver aprobación</summary><p>${esc(d.evidence)}</p></details></article>`).join('');}
function renderComments(){$('#comments').innerHTML=project.feedback.filter(f=>f.element_id===selected?.id).map(f=>`<div class="comment-item">${esc(f.text)}<br><small>${esc(f.revision_id)}</small></div>`).join('');}
function download(name,content,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
$('#layer-search').addEventListener('input',()=>project&&renderLayers());
$('#layers').addEventListener('click',event=>{const button=event.target.closest('[data-id]');if(!button||busy||pending)return;const n=project.manifest.find(n=>n.id===button.dataset.id);showSelection(n);postSelection(true);});
addEventListener('message',event=>{const d=event.data;if(event.source!==frame.contentWindow||event.origin!=='null'||!d||d.nonce!==nonce||d.project_id!==project?.project_id||d.revision_id!==frameRevision)return;
 if(d.type==='ve:ready'){ready=true;config();if(!comparing&&!pending)syncCanvas();postSelection();return;}
 if(d.type==='ve:flushed'){flushes.get(d.request_id)?.();flushes.delete(d.request_id);return;}
 if(d.type==='ve:gesture'){gesturing=d.active===true;updateButtons();return;}
 if(d.type==='ve:change'){recordChange(d.element_id,{...('text'in d?{text:d.text}:{}),...(d.styles?{styles:d.styles}:{})},typeof d.transaction==='string'?d.transaction.slice(0,80):undefined,true);return;}
 if(d.type==='ve:shortcut'){if(d.command==='save')save();else if(d.command==='undo')undo();else if(d.command==='redo')redo();return;}
 if(d.type==='ve:selected'&&!pending&&!busy){const n=project.manifest.find(n=>n.id===d.element_id);if(n)showSelection(n,d.styles);}
});
$$('[data-prop]').forEach(input=>{let transaction;input.addEventListener('focus',()=>transaction=crypto.randomUUID());input.addEventListener('input',()=>{if(!input.checkValidity())return;let value=input.value;if(!['color','background-color','font-family','font-weight','line-height'].includes(input.dataset.prop))value+='px';recordChange(selected.id,{styles:{[input.dataset.prop]:value}},transaction);});});
let textTransaction;$('#text-edit').addEventListener('focus',()=>textTransaction=crypto.randomUUID());$('#text-edit').addEventListener('input',()=>recordChange(selected.id,{text:$('#text-edit').value},textTransaction));
async function save(){if(busy||pending||!editable())return;await flushCanvas();if(!dirty())return;lock(async()=>{saveKey??=crypto.randomUUID();const result=await action('save_canvas_changes',{expected_revision:project.head,changes:changesToSave(),idempotency_key:saveKey});await load();status(`Guardado · ${result.revision_id} · cambios registrados para el agente · borrador fuente`);});}
$('#save').onclick=save;
$('#inspector').addEventListener('submit',event=>{event.preventDefault();lock(async()=>{pending=await action('propose_changes',{base_revision:project.head,changes:changesToSave()});$('#diff-list').innerHTML=pending.diff.map(d=>`<article class="diff-item"><h3>${esc(d.label)} · ${esc(d.property)} · ${esc(d.viewport||'global')}</h3><p class="diff-before">− ${esc(d.before)}</p><p class="diff-after">+ ${esc(d.after)}</p><p>${esc(d.file)}${d.line?':'+d.line:''}</p></article>`).join('');renderFrame(pending.preview_revision);$('#review-dialog').showModal();status('Revisión lista · falta guardar');});});
async function cancelReview(){if(!pending||busy)return;await lock(async()=>{await action('discard_changes',{patch_id:pending.patch_id,expected_revision:pending.base_revision});pending=null;$('#review-dialog').close();renderFrame();status('Revisión cerrada · los ajustes siguen en el lienzo');});}
$('#cancel-review').onclick=cancelReview;$('#cancel-review-bottom').onclick=cancelReview;$('#review-dialog').addEventListener('cancel',e=>{e.preventDefault();cancelReview();});
$('#commit').onclick=()=>lock(async()=>{await action('apply_changes',{patch_id:pending.patch_id,expected_revision:project.head});pending=null;$('#review-dialog').close();await load();});
async function undo(){if(busy||pending||comparing||viewRevision||gesturing)return;await flushCanvas();if(undoLocal.length){const step=undoLocal.pop();redoLocal.push(step);working=copy(step.before);saveKey=null;syncCanvas();if(selected)showSelection(selected);updateButtons();status(dirty()?'Deshecho · quedan ajustes sin guardar':'Deshecho · sin ajustes pendientes');return;}if(project.canUndo)lock(async()=>{await action('undo',{expected_revision:project.head});await load();});}
async function redo(){if(busy||pending||comparing||viewRevision||gesturing)return;if(redoLocal.length){const step=redoLocal.pop();undoLocal.push(step);working=copy(step.after);saveKey=null;syncCanvas();if(selected)showSelection(selected);updateButtons();status('Rehecho · sin guardar');return;}if(!dirty()&&project.canRedo)lock(async()=>{await action('redo',{expected_revision:project.head});await load();});}
$('#undo').onclick=undo;$('#redo').onclick=redo;
$('#history').onclick=event=>{const b=event.target.closest('[data-restore]');if(!b||busy||viewRevision||dirty()&&!confirm('Hay ajustes sin guardar. ¿Descartarlos para restaurar?'))return;lock(async()=>{await action('restore_revision',{revision_id:b.dataset.restore,expected_revision:project.head});await load();});};
$('#compare').onclick=()=>{if(pending||busy)return;if(viewRevision){viewRevision=null;viewEdits=null;history.replaceState(null,'','/');$('#compare').textContent='Ver original';load().catch(e=>status(e.message,true));return;}comparing=!comparing;$('#compare').textContent=comparing?'Volver al borrador':'Ver original';renderFrame();updateButtons();};
$$('[data-width]').forEach(button=>button.onclick=async()=>{await flushCanvas();viewport=Number(button.dataset.width);$$('[data-width]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});sizeFrame();});
$$('[data-tab]').forEach(button=>button.onclick=()=>{$$('[data-tab]').forEach(b=>{b.setAttribute('aria-selected',String(b===button));$('#'+b.dataset.tab+'-panel').hidden=b!==button;});});
$('#export').onclick=()=>lock(async()=>{const result=await action('export_patch',{revision_id:viewRevision||project.head});download(`source-draft-${viewRevision||project.head}.json`,JSON.stringify(result,null,2));status('Borrador guardado exportado · requiere revisión antes de integrar');});
$('#export-unsaved').onclick=()=>download('unsaved-canvas-changes.json',JSON.stringify({project_id:project.project_id,base_revision:project.head,changes:changesToSave(),draft_only:true,deployed:false},null,2));
$('#export-taste').onclick=()=>lock(async()=>{const result=await action('export_web_taste',{approved_revision:project.taste.revision});download(result.filename,result.content,'text/markdown');status('web-taste.md exportado · decisiones aprobadas');});
$('#add-comment').onclick=()=>lock(async()=>{await action('add_feedback',{element_id:selected.id,text:$('#comment').value,expected_revision:project.head});$('#comment').value='';await load({preserveInputs:true});renderComments();});
addEventListener('resize',sizeFrame);addEventListener('beforeunload',event=>{if(dirty()){event.preventDefault();event.returnValue='';}});
addEventListener('keydown',event=>{if(!(event.ctrlKey||event.metaKey))return;const key=event.key.toLowerCase();if(key==='s'){event.preventDefault();save();}else if(['z','y'].includes(key)&&!event.target.matches('input,textarea,[contenteditable]')){event.preventDefault();key==='y'||event.shiftKey?redo():undo();}});
if(viewRevision)$('#compare').textContent='Volver al borrador';
load().catch(error=>{$('#loading').textContent=error.message;status(error.message,true);});
