'use strict';
const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const frame=$('#preview');let project,selected,changes={},textChanged=false,viewport=1440,nonce,frameRevision,comparing=false,pending,busy=false;let viewRevision=new URL(location.href).searchParams.get('revision'),viewEdits=null;
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function status(text,error=false){$('#status').textContent=text;$('#status').toggleAttribute('data-error',error);}
async function action(name,args={}){const response=await fetch('/api/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:name,args})});const result=await response.json();if(!response.ok)throw new Error(result.error?.message||'No se pudo guardar');return result;}
async function lock(fn){if(busy)return;busy=true;$$('#commit,#review,#undo,#redo,#export,#add-comment,#cancel-review,#cancel-review-bottom,#inspector input,#inspector textarea,#inspector select').forEach(x=>x.disabled=true);try{await fn();}catch(error){status(error.message,true);}finally{busy=false;updateButtons();}}
function updateButtons(){if(!project)return;$('#undo').disabled=busy||!project.canUndo||!!viewRevision;$('#redo').disabled=busy||!project.canRedo||!!viewRevision;$('#export').disabled=busy;$('#review').disabled=busy||(!textChanged&&!Object.keys(changes).length)||comparing||!!viewRevision;$('#commit').disabled=busy||!pending;$$('#inspector input,#inspector textarea,#inspector select').forEach(x=>x.disabled=busy||comparing||!!viewRevision);$('#add-comment').disabled=busy||!selected||!!viewRevision;$('#cancel-review').disabled=busy;$('#cancel-review-bottom').disabled=busy;}
async function load({preserveInputs=false}={}){
  const response=await fetch('/api/project');const data=await response.json();if(!response.ok)throw new Error(data.error?.message||'No se pudo abrir el proyecto');project=data;$('[data-prop="font-family"]').innerHTML=project.available_fonts.map(f=>`<option>${esc(f)}</option>`).join('');$('.project-heading strong').textContent=project.name;$('.project-heading div>span').textContent=project.subtitle;$('.frame-caption>span').textContent=project.pageLabel+' / INICIO';$('.source-version').textContent=project.revisionLabel;document.title='Atelier · '+project.name;if(viewRevision){if(!project.history.some(r=>r.id===viewRevision))throw new Error('La revisión del enlace no existe');const inspected=await action('inspect_page',{page_id:'home',revision_id:viewRevision});viewEdits=Object.fromEntries(inspected.elements.map(n=>[n.id,{...(n.text!==null?{text:n.text}:{}),styles:n.overrides}]));}
  renderLayers();renderHistory();renderTaste();updateButtons();$('#loading').hidden=true;
  if(!preserveInputs){changes={};textChanged=false;renderFrame();if(selected)showSelection(selected);}
  status(viewRevision?`Viendo ${viewRevision} · solo lectura · actual ${project.head}`:`Guardado · ${project.head} · borrador fuente`);
}
function displayedText(node){return (viewEdits||project.edits)[node.id]?.text??node.text??'';}
function displayedLabel(node){return node.text&&node.label===node.text.slice(0,38)?displayedText(node).slice(0,38):node.label;}
function renderLayers(){const query=$('#layer-search').value.toLowerCase();const rows=project.manifest.filter(n=>!query||`${displayedLabel(n)} ${displayedText(n)}`.toLowerCase().includes(query));$('#layer-count').textContent=`${project.manifest.length}`;$('#layers').innerHTML=rows.map(n=>`<button class="layer ${selected?.id===n.id?'selected':''}" data-id="${n.id}" data-depth="${Math.min(n.depth,4)}"><span class="layer-symbol">${/^h[123]$/.test(n.tag)?'T':n.text?'t':'◇'}</span><span class="layer-label">${esc(displayedLabel(n))}</span></button>`).join('');}
function sizeFrame(){const available=$('.canvas-scroll').clientWidth-(innerWidth<560?24:innerWidth<1100?30:48);const scale=Math.min(1,available/viewport);const height=900;frame.style.width=viewport+'px';frame.style.height=height+'px';frame.style.transform=`scale(${scale})`;$('#frame-wrap').style.width=viewport*scale+'px';$('#frame-wrap').style.height=height*scale+'px';$('.frame-caption').style.width=viewport*scale+'px';$('#zoom').textContent=Math.round(scale*100)+'%';$('#viewport-label').textContent=`${viewport} × ${height}`;if(selected&&!textChanged&&!Object.keys(changes).length)requestAnimationFrame(()=>postSelection());}
function renderFrame(rev){nonce=crypto.randomUUID();frameRevision=rev|| (comparing?'r0':viewRevision||project.head);frame.src=`/preview?revision=${encodeURIComponent(frameRevision)}&nonce=${nonce}`;$('#revision-badge').textContent=comparing?'ORIGINAL · r0':frameRevision.startsWith('patch:')?'PROPUESTA':frameRevision;sizeFrame();}
function postSelection(scroll=false){if(!selected)return;frame.contentWindow.postMessage({type:'ve:select',project_id:project.project_id,revision_id:frameRevision,nonce,element_id:selected.id,scroll},'*');}
function showSelection(node,computed){selected=node;changes={};textChanged=false;$('#selection-empty').hidden=true;$('#inspector').hidden=false;$('#element-tag').textContent=node.tag;$('#element-name').textContent=displayedLabel(node);$('#source-map').textContent=`${node.source.file}:${node.source.line}`;$('#selection-path').textContent=`${node.tag} / ${displayedLabel(node)}`;$('#text-label').hidden=!node.editable.text;$('#text-edit').disabled=comparing||!!viewRevision;$('#text-edit').value=(viewEdits||project.edits)[node.id]?.text??node.text??'';$('#locked-reason').textContent=node.lockedReason||'';$('#locked-reason').hidden=!node.lockedReason;fillStyles(computed||{});renderLayers();renderComments();updateButtons();}
function toHex(value){if(/^#[\da-f]{6}$/i.test(value))return value;const m=value?.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);return m?'#'+m.slice(1).map(x=>Number(x).toString(16).padStart(2,'0')).join(''):'#111110';}
function fillStyles(computed){const saved=(viewEdits||project.edits)[selected.id]?.styles||{};for(const input of $$('[data-prop]')){const prop=input.dataset.prop;let value=saved[prop]??computed[prop]??'';if(prop==='font-family'){value=value.split(',')[0].replaceAll('"','').replaceAll("'",'').trim();if(![...input.options].some(x=>x.value===value))value='Arial';}else if(prop==='color'||prop==='background-color')value=toHex(value);else if(prop==='line-height'){const n=Number.parseFloat(value);value=value.includes('px')?(n/(Number.parseFloat(computed['font-size'])||16)).toFixed(2):Number.isFinite(n)?n:1.2;}else if(prop!=='font-weight'){value=Number.parseFloat(value);if(!Number.isFinite(value))value=0;}input.value=value;input.disabled=comparing||!!viewRevision;}}
function renderHistory(){$('#history').innerHTML=[...project.history].reverse().map(r=>`<article class="history-item"><strong>${esc(r.id)} · ${esc(r.label)}</strong><p>${esc(new Date(r.createdAt).toLocaleString('es'))}</p>${r.id===project.head?'<span class="current">REVISIÓN ACTUAL</span>':`<button data-restore="${r.id}">Restaurar esta revisión ↶</button>`}</article>`).join('');}
function renderTaste(){$('#taste-rules').innerHTML=project.taste.decisions.map(d=>`<article class="taste-rule"><h3>${esc(d.scope)}</h3><p>${esc(d.rule)}</p><details><summary>Ver aprobación</summary><p>${esc(d.evidence)}</p></details></article>`).join('');}
function renderComments(){$('#comments').innerHTML=project.feedback.filter(f=>f.element_id===selected?.id).map(f=>`<div class="comment-item">${esc(f.text)}<br><small>${esc(f.revision_id)}</small></div>`).join('');}
function download(name,content,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
$('#layer-search').addEventListener('input',()=>project&&renderLayers());
$('#layers').addEventListener('click',event=>{const button=event.target.closest('[data-id]');if(!button||busy||pending)return;const node=project.manifest.find(n=>n.id===button.dataset.id);if((textChanged||Object.keys(changes).length)&&!confirm('Hay ajustes sin guardar. ¿Descartarlos y seleccionar otro elemento?'))return;showSelection(node);postSelection(true);});
addEventListener('message',event=>{const data=event.data;if(event.source!==frame.contentWindow||event.origin!=='null'||!data||data.nonce!==nonce||data.project_id!==project?.project_id||data.revision_id!==frameRevision)return;if(data.type==='ve:ready'){postSelection();return;}if(data.type!=='ve:selected'||pending||busy)return;const node=project.manifest.find(n=>n.id===data.element_id);if(!node)return;if(selected?.id===node.id&&(textChanged||Object.keys(changes).length))return;if(selected?.id!==node.id&&(textChanged||Object.keys(changes).length)&&!confirm('Hay ajustes sin guardar. ¿Descartarlos y seleccionar otro elemento?')){postSelection();return;}showSelection(node,data.styles);});
$$('[data-prop]').forEach(input=>input.addEventListener('input',()=>{let value=input.value;if(!['color','background-color','font-family','font-weight','line-height'].includes(input.dataset.prop))value+='px';changes[input.dataset.prop]=value;updateButtons();status('Ajustes sin guardar · revisá los cambios');}));
$('#text-edit').addEventListener('input',()=>{textChanged=true;updateButtons();status('Texto sin guardar · revisá los cambios');});
$('#inspector').addEventListener('submit',event=>{event.preventDefault();lock(async()=>{const change={element_id:selected.id};if(textChanged)change.text=$('#text-edit').value;if(Object.keys(changes).length)change.styles=changes;pending=await action('propose_changes',{base_revision:project.head,changes:[change]});$('#diff-list').innerHTML=pending.diff.map(d=>`<article class="diff-item"><h3>${esc(d.label)} · ${esc(d.property)}</h3><p class="diff-before">− ${esc(d.before)}</p><p class="diff-after">+ ${esc(d.after)}</p><p>${esc(d.file)}${d.line?':'+d.line:''}</p></article>`).join('');renderFrame(pending.preview_revision);$('#review-dialog').showModal();status('Propuesta lista · falta guardar');});});
async function cancelReview(){if(!pending||busy)return;await lock(async()=>{await action('discard_changes',{patch_id:pending.patch_id,expected_revision:pending.base_revision});pending=null;$('#review-dialog').close();renderFrame();status('Propuesta descartada · los ajustes siguen en el panel');});}
$('#cancel-review').onclick=cancelReview;$('#cancel-review-bottom').onclick=cancelReview;$('#review-dialog').addEventListener('cancel',event=>{event.preventDefault();cancelReview();});
$('#commit').onclick=()=>lock(async()=>{await action('apply_changes',{patch_id:pending.patch_id,expected_revision:project.head});pending=null;$('#review-dialog').close();await load();});
function confirmDirty(){return (!textChanged&&!Object.keys(changes).length)||confirm('Hay ajustes sin guardar. ¿Descartarlos para cambiar de revisión?');}
$('#undo').onclick=()=>confirmDirty()&&lock(async()=>{await action('undo',{expected_revision:project.head});await load();});$('#redo').onclick=()=>confirmDirty()&&lock(async()=>{await action('redo',{expected_revision:project.head});await load();});
$('#history').onclick=event=>{const button=event.target.closest('[data-restore]');if(!button||!confirmDirty())return;lock(async()=>{await action('restore_revision',{revision_id:button.dataset.restore,expected_revision:project.head});await load();});};
$('#compare').onclick=()=>{if(pending||busy)return;if(viewRevision){viewRevision=null;viewEdits=null;history.replaceState(null,'','/');$('#compare').textContent='Ver original';load().catch(e=>status(e.message,true));return;}if(textChanged||Object.keys(changes).length){status('Revisá o guardá los ajustes antes de comparar',true);return;}comparing=!comparing;$('#compare').textContent=comparing?'Volver al borrador':'Ver original';$('#text-edit').disabled=comparing;renderFrame();updateButtons();};
$$('[data-width]').forEach(button=>button.onclick=()=>{viewport=Number(button.dataset.width);$$('[data-width]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});sizeFrame();});
$$('[data-tab]').forEach(button=>button.onclick=()=>{$$('[data-tab]').forEach(b=>{b.setAttribute('aria-selected',String(b===button));$('#'+b.dataset.tab+'-panel').hidden=b!==button;});});
$('#export').onclick=()=>lock(async()=>{const result=await action('export_patch',{revision_id:viewRevision||project.head});download(`source-draft-${viewRevision||project.head}.json`,JSON.stringify(result,null,2));status('Borrador exportado · requiere revisión antes de integrar');});
$('#export-taste').onclick=()=>lock(async()=>{const result=await action('export_web_taste',{approved_revision:project.taste.revision});download(result.filename,result.content,'text/markdown');status('web-taste.md exportado · decisiones aprobadas');});
$('#add-comment').onclick=()=>lock(async()=>{await action('add_feedback',{element_id:selected.id,text:$('#comment').value,expected_revision:project.head});$('#comment').value='';await load({preserveInputs:true});renderComments();});
addEventListener('resize',sizeFrame);addEventListener('beforeunload',event=>{if(textChanged||Object.keys(changes).length){event.preventDefault();event.returnValue='';}});
if(viewRevision)$('#compare').textContent='Volver al borrador';
load().catch(error=>{$('#loading').textContent=error.message;status(error.message,true);});
