import {applyOperations,v2Preview} from '/v2-runtime.js';
const $=s=>document.querySelector(s),clone=x=>structuredClone(x),frame=$('#canvas');
let data,documentState,selected=null,viewport='desktop',pending=[],redo=[],saving=null,timer,nonce,scrollY=0,editing=false,gesture=false,clipboard=null,conflict=false,historyBusy=false;
const flushWaiters=new Map(),measurements=new Map();
const widths={desktop:1280,tablet:820,mobile:390};
const status=(text,error=false)=>{$('#status').textContent=text;$('#status').style.color=error?'#f3b9a4':'';};
const node=id=>documentState?.nodes.find(n=>n.id===id&&!n.deleted);
const native=e=>e.target?.closest('input,textarea,select,[contenteditable]');
const localKey=()=>`web-studio-v2:${data.project.id}:${data.sourceFingerprint}`;
function persist(){try{if(pending.length)localStorage.setItem(localKey(),JSON.stringify({head:data.head,pending,sourceFingerprint:data.sourceFingerprint}));else localStorage.removeItem(localKey());}catch{status('El navegador no permite recuperación local; usá Guardar',true);}}
function download(value,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
async function api(action,args={}){const r=await fetch('/api/v2/'+action,{method:action==='load'?'GET':'POST',headers:{'content-type':'application/json'},...(action==='load'?{}:{body:JSON.stringify(args)})});const json=await r.json();if(!r.ok)throw Object.assign(new Error(json.error?.message||'No se pudo guardar'),{code:json.error?.code});return json;}
function recompute(){documentState=pending.length?applyOperations(data.snapshot,data.document,pending.flatMap(p=>p.operations),{fontChoices:data.fonts}):clone(data.document);}
function send(type,extra={}){frame.contentWindow?.postMessage({type,nonce,project_id:data.project.id,...extra},'*');}
function scaleCanvas(){const width=widths[viewport],available=Math.max(180,$('#canvas-wrap').clientWidth-44),scale=$('#zoom').value==='fit'?Math.min(1,available/width):Number($('#zoom').value);frame.style.width=width+'px';frame.style.transform=`scale(${scale})`;$('#canvas-size').style.width=width*scale+'px';$('#canvas-size').style.height=920*scale+'px';}
function preview(){nonce=crypto.randomUUID();frame.srcdoc=v2Preview(data.snapshot,documentState,data.assets,{nonce,cspNonce:document.querySelector('meta[name=v2-preview-nonce]')?.content,project_id:data.project.id,viewport,selected,scrollY});scaleCanvas();}
function renderLayers(){const host=$('#layers');host.replaceChildren();let count=0;function visit(id,depth=0){const n=node(id);if(!n)return;count++;const b=document.createElement('button');b.className='layer';b.dataset.id=id;b.setAttribute('role','treeitem');b.setAttribute('aria-selected',String(id===selected));b.style.paddingLeft=8+depth*12+'px';b.textContent=`${n.tag}  ${n.label}`;b.addEventListener('click',()=>select(id));host.append(b);for(const c of n.children)visit(c,depth+1);}for(const id of documentState.roots)visit(id);$('#layer-count').textContent=count;}
function buttons(){$('.workspace').inert=historyBusy;$('#undo').disabled=historyBusy||!(pending.length||data.canUndo)||editing||gesture;$('#redo').disabled=historyBusy||!(redo.length||data.canRedo)||editing||gesture;$('#save').disabled=historyBusy||(!pending.length&&!editing)||!!saving||conflict;$('#export').disabled=historyBusy||!!pending.length||!!saving||editing;$('#paste').disabled=!clipboard||conflict;$('#migrate').disabled=data.history.length!==1||!!pending.length||!!saving;}
function renderInspector(){const n=node(selected);$('#empty').hidden=!!n;$('#selection').hidden=!n;if(!n)return;$('#layer-name').textContent=n.label;$('#source').textContent=`${n.id} · ${n.tag} · línea ${n.source?.line||'—'}`;$('#locked').textContent=n.lockedReason||'';$('#text-row').hidden=!n.editable.text;$('#edit-text').hidden=!n.editable.text;$('#text').value=n.text??'';const measured=measurements.get(viewport+':'+n.id)||{},layout=n.responsiveLayout?.[viewport]||n.layout||{mode:['absolute','fixed'].includes(measured.position)?'source':'flow',x:parseFloat(measured.left)||0,y:parseFloat(measured.top)||0};$('#layout').value=layout.mode;$('#coords').hidden=layout.mode!=='free';$('#x').value=layout.x||0;$('#y').value=layout.y||0;const styles={...n.styles,...n.responsive?.[viewport]};const family=(measured.fontFamily||'').split(',')[0].trim().replaceAll('\"','').replaceAll("'",'');$('#font').value=styles['font-family']||(data.fonts.includes(family)?family:'');$('#size').value=parseFloat(styles['font-size']||measured.fontSize)||'';const rgb=(measured.color||'').match(/\d+/g);$('#color').value=styles.color||(rgb?.length>=3?'#'+rgb.slice(0,3).map(v=>Number(v).toString(16).padStart(2,'0')).join(''):'#111111');const p=$('#parent');p.replaceChildren(new Option('Página', ''));for(const parent of documentState.nodes.filter(x=>!x.deleted&&x.id!==n.id&&!['img','br','hr','input'].includes(x.tag)))p.add(new Option(`${parent.tag} · ${parent.label}`,parent.id));p.value=n.parentId||'';}
function render(){if(selected&&!node(selected))selected=null;renderLayers();renderInspector();buttons();preview();}
function select(id,fromFrame=false){const next=node(id)?id:null,same=next===selected;selected=next;renderLayers();const fieldActive=document.activeElement?.closest('.inspector')&&document.activeElement?.matches('input,textarea,select,[contenteditable]');if(!(fromFrame&&same&&fieldActive))renderInspector();buttons();if(!fromFrame)send('v2:select',{id:selected});}
function command(operations){if(historyBusy){status('Esperá a que termine el cambio de historial',true);return false;}if(conflict){status('Conflicto: descargá tus cambios antes de recargar',true);return;}try{if(pending.length>=90)throw new Error('Hay demasiados cambios pendientes; guardá o descargá la recuperación antes de continuar');const group={operations:Array.isArray(operations)?operations:[operations],key:crypto.randomUUID()};documentState=applyOperations(data.snapshot,documentState,group.operations,{fontChoices:data.fonts});pending.push(group);redo=[];persist();render();status('Cambios locales · guardando borrador…');clearTimeout(timer);timer=setTimeout(()=>flush(),700);return true;}catch(e){status(e.message,true);return false;}}
function flushCanvas(){if(!editing)return Promise.resolve();const requestId=crypto.randomUUID();return new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{flushWaiters.delete(requestId);reject(new Error('Terminá el texto con Enter antes de continuar'));},2000);flushWaiters.set(requestId,{nonce,resolve:()=>{clearTimeout(timeout);resolve();}});send('v2:commit-text',{requestId});});}
async function flush(){clearTimeout(timer);if(saving)return saving;try{await flushCanvas();}catch(e){status(e.message,true);return;}if(saving)return saving;if(!pending.length||conflict)return;saving=(async()=>{while(pending.length&&!conflict){const group=pending[0];group.baseRevision??=data.head;persist();status('Guardando borrador…');try{const next=await api('save',{expected_revision:group.baseRevision,operations:group.operations,idempotency_key:group.key});data=next;pending.shift();recompute();persist();buttons();}catch(e){conflict=e.code==='REVISION_CONFLICT'||e.code==='SOURCE_MISMATCH';status(e.message+' Tus cambios locales se conservan.',true);$('#recovery').hidden=false;return;}}status('Guardado · '+data.head);})().finally(()=>{saving=null;buttons();});buttons();return saving;}
async function history(direction){if(editing||gesture||historyBusy)return;historyBusy=true;buttons();try{if(saving)await saving;if(conflict)return;if(direction==='undo'&&pending.length){redo.push(pending.pop());recompute();persist();render();status('Cambio deshecho');return;}if(direction==='redo'&&redo.length){pending.push(redo.pop());recompute();persist();render();clearTimeout(timer);timer=setTimeout(()=>flush(),700);return;}await flush();if(conflict)return;try{data=await api(direction,{expected_revision:data.head});documentState=clone(data.document);redo=[];render();status('Guardado · '+data.head);}catch(e){status(e.message,true);}}finally{historyBusy=false;buttons();}}
function copy(cut=false){if(!node(selected))return;clipboard={id:selected,cut,project:data.project.id,fingerprint:data.sourceFingerprint};const text='web-studio-layer-v2:'+JSON.stringify(clipboard);navigator.clipboard?.writeText(text).catch(()=>{});status(cut?'Capa marcada para cortar; pegá en el padre elegido':'Capa copiada; disponible dentro de este editor');buttons();}
function paste(){if(!clipboard||clipboard.project!==data.project.id||clipboard.fingerprint!==data.sourceFingerprint||!node(clipboard.id)){status('Copiá una capa de este borrador primero',true);return;}const target=node(selected),parentId=target?.parentId??null,siblings=(parentId?node(parentId).children:documentState.roots).filter(id=>node(id)&&(!clipboard.cut||id!==clipboard.id)),index=target&&siblings.includes(target.id)?siblings.indexOf(target.id)+1:siblings.length;const applied=command({type:clipboard.cut?'move':'duplicate',id:clipboard.id,parentId,index});if(applied&&clipboard.cut)clipboard=null;buttons();}
function nudge(key,shift=false){const n=node(selected);if(!n)return;if(!n.layout&&!n.responsiveLayout?.[viewport]&&!measurements.has(viewport+':'+n.id)){status('Esperá a que el lienzo mida esta capa antes de moverla');return;}const measured=measurements.get(viewport+':'+n.id)||{},layout=n.responsiveLayout?.[viewport]||n.layout||{mode:['absolute','fixed'].includes(measured.position)?'source':'flow',x:parseFloat(measured.left)||0,y:parseFloat(measured.top)||0},delta=key==='ArrowUp'||key==='ArrowLeft'?-1:1;if(layout.mode==='source'){status('Elegí Libre para declarar coordenadas respecto al padre antes de mover esta capa',true);return;}if(layout.mode==='free'){const axis=key==='ArrowLeft'||key==='ArrowRight'?'x':'y';command({type:'layout',id:n.id,mode:'free',x:layout.x||0,y:layout.y||0,[axis]:Math.max(-4096,Math.min(4096,(layout[axis]||0)+delta*(shift?10:1))),viewport});}else{const siblings=(n.parentId?node(n.parentId).children:documentState.roots).filter(id=>node(id));const index=Math.max(0,Math.min(siblings.length-1,siblings.indexOf(n.id)+delta));if(index!==siblings.indexOf(n.id))command({type:'move',id:n.id,parentId:n.parentId,index});}}
function shortcut(key,shift){if(key==='s'){flush();return;}if(key==='z'){history(shift?'redo':'undo');return;}if(key==='y'){history('redo');return;}if(key==='c')copy();if(key==='x')copy(true);if(key==='v')paste();}
document.addEventListener('keydown',e=>{if(e.isComposing)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();if(native(e))e.target.blur();flush();return;}if(native(e))return;if((e.ctrlKey||e.metaKey)&&['z','y','c','x','v','s'].includes(e.key.toLowerCase())){e.preventDefault();shortcut(e.key.toLowerCase(),e.shiftKey);}else if(selected&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();nudge(e.key,e.shiftKey);}else if(selected&&['Backspace','Delete'].includes(e.key)){e.preventDefault();command({type:'delete',id:selected});}});
window.addEventListener('message',e=>{const m=e.data;if(e.source!==frame.contentWindow||!m||m.project_id!==data?.project.id)return;if(m.type==='v2:flushed'){const waiter=flushWaiters.get(m.requestId);if(waiter&&waiter.nonce===m.nonce){flushWaiters.delete(m.requestId);editing=false;if(m.operation)command(m.operation);waiter.resolve();}return;}if(m.nonce!==nonce)return;if(m.type==='v2:save-text'){editing=false;if(m.operation)command(m.operation);flush();return;}if(m.type==='v2:select'){if(m.computed&&node(m.id))measurements.set(viewport+':'+m.id,m.computed);select(m.id,true);}if(m.type==='v2:operation'){editing=false;gesture=false;command(m.operation);}if(m.type==='v2:shortcut')shortcut(m.key,m.shift);if(m.type==='v2:nudge')nudge(m.key,m.shift);if(m.type==='v2:blocked')status(String(m.message||'Elegí un modo de disposición'),true);if(m.type==='v2:scroll'&&Number.isFinite(m.scrollY))scrollY=m.scrollY;if(m.type==='v2:editing'){editing=!!m.active;buttons();}if(m.type==='v2:gesture'){gesture=!!m.active;buttons();}});
$('#undo').onclick=()=>history('undo');$('#redo').onclick=()=>history('redo');$('#save').onclick=()=>flush();$('#export').onclick=async()=>{try{download(await api('export'),'studio-v2-source-draft.json');}catch(e){status(e.message,true);}};
$('#delete').onclick=()=>command({type:'delete',id:selected});$('#edit-text').onclick=()=>send('v2:edit');$('#text').addEventListener('change',()=>{if(node(selected)&&$('#text').value!==node(selected).text)command({type:'text',id:selected,text:$('#text').value});});
$('#copy').onclick=()=>copy();$('#cut').onclick=()=>copy(true);$('#paste').onclick=paste;
for(const [id,delta] of [['up',-1],['down',1]])$('#'+id).onclick=()=>{const n=node(selected),siblings=(n.parentId?node(n.parentId).children:documentState.roots).filter(x=>node(x));command({type:'move',id:selected,parentId:n.parentId,index:Math.max(0,Math.min(siblings.length-1,siblings.indexOf(n.id)+delta))});};
$('#reparent').onclick=()=>command({type:'move',id:selected,parentId:$('#parent').value||null,index:0});
function layout(){command({type:'layout',id:selected,mode:$('#layout').value,...($('#layout').value==='free'?{x:Number($('#x').value)||0,y:Number($('#y').value)||0}:{}),viewport});}
$('#layout').onchange=layout;$('#x').onchange=layout;$('#y').onchange=layout;
for(const [id,property] of [['font','font-family'],['size','font-size'],['color','color']])$('#'+id).onchange=()=>command({type:'style',id:selected,styles:{[property]:$('#'+id).value+(id==='size'?'px':'')},viewport});
for(const b of document.querySelectorAll('[data-view]'))b.onclick=async()=>{try{await flushCanvas();}catch(e){status(e.message,true);return;}viewport=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderInspector();preview();};
$('#zoom').onchange=scaleCanvas;new ResizeObserver(scaleCanvas).observe($('#canvas-wrap'));
$('#recovery').onclick=()=>download({schemaVersion:2,sourceFingerprint:data.sourceFingerprint,base_revision:data.head,pending,document:documentState},'studio-v2-local-recovery.json');
$('#migrate').onclick=async()=>{try{data=await api('migrate_v1',{expected_revision:data.head,v1_revision:$('#v1-revision').value});documentState=clone(data.document);render();status('Copia V1 guardada en V2');}catch(e){status(e.message,true);}};
window.addEventListener('beforeunload',e=>{if(pending.length){persist();e.preventDefault();e.returnValue='';}});
try{data=await api('load');documentState=clone(data.document);$('#project-name').textContent=data.project.name;const inherited=new Option('Fuente original','');inherited.disabled=true;$('#font').add(inherited);for(const f of data.fonts)$('#font').add(new Option(f,f));let recovery;try{recovery=JSON.parse(localStorage.getItem(localKey())||'null');}catch{}if(recovery?.pending?.length&&recovery.sourceFingerprint===data.sourceFingerprint){pending=recovery.pending;if(recovery.head!==data.head){conflict=true;status('Hay cambios locales de otra revisión. Descargalos antes de recargar.',true);$('#recovery').hidden=false;}else{recompute();status('Borrador local recuperado');setTimeout(()=>flush(),700);}}else status('Guardado · '+data.head);render();}catch(e){status(e.message,true);}
